version: '3'

services:
  post-api:
    container_name: post-api
    depends_on:
      - post-db
    image: ghcr.io/numaleone/jibber-jabber-posts-leone-alvarado:main
    ports:
      - 8081:8080
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: postgres
      DB_HOST: host.docker.internal
      DB_PORT: 5433

      DD_API_KEY:
      DD_SITE: datadoghq.com
      DD_LOGS_ENABLED: 1
      DD_APM_ENABLED: 1
      DD_STEP: PT10S


  post-db:
    container_name: post_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db
#      volumes:
#        - pgdata:/var/lib/postgresql/data


  follow-api:
    container_name: follow-api
    depends_on:
      - follow_db
    ports:
      - 8082:8080
#    image: ghcr.io/nico-werner/jibberjabber-followers-api:${environment}
    image: ghcr.io/numaleone/jibber-jabber-followers:main
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: postgres
      DB_HOST: host.docker.internal
      DB_PORT: 5436

      DD_API_KEY:
      DD_SITE: datadoghq.com
      DD_LOGS_ENABLED: 1
      DD_APM_ENABLED: 1
      DD_STEP: PT10S

  follow_db:
    container_name: follow_db
    image: postgres:12
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: follow-db
#    volumes:
#      - followdata:/var/lib/postgresql/data
  datadog:
    image: datadog/agent
    environment:
      - DD_API_KEY=
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_STEP=PT10S
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'



  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    depends_on:
      - keycloak-db
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      PROXY_ADDRESS_FORWARDING: 1
      KC_PROXY: passthrough
      KEYCLOAK_PROXY: passthrough

  keycloak-db:
    container_name: keycloak-db
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
#    volumes:
#      - keycloakdata:/var/lib/postgresql/data




